export type CalendarBlock = {
  schedule_block_id: number;
  order_id: number;
  user_id: number;
  task_type_id: number | null;
  user_name: string;
  block_start: string;
  block_end: string;
  block_duration_minutes: number;
  block_status: "geplant" | "in_arbeit" | "pausiert" | "erledigt";
  block_source: "manual" | "auto";
  block_notes: string | null;
  order_number: string | null;
  title: string;
  vehicle_info: string | null;
  license_plate: string | null;
  price: string | number | null;
  currency: string;
  order_status: string;
  priority: string;
  order_estimated_duration_minutes: number | null;
  is_internal: number;
  order_notes: string | null;
  customer_id: number;
  customer_name: string;
  customer_phone: string | null;
  customer_email: string | null;
  task_type_name: string | null;
  task_type_color: string | null;
};